apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-journal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-journal
  template:
    metadata:
      labels:
        app: ops-journal
    spec:
      containers:
        - name: ops-journal
          image: ops-journal:0.1
          ports:
            - containerPort: 80

